apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 30; done;"]
    volumeMounts:
    - mountPath: "/mnt/data"
      name: wordpress-storage
  volumes:
  - name: wordpress-storage
    persistentVolumeClaim:
      claimName: wordpress-pvc
